// Exercício LeetCode: Remover todas as duplicatas adjacentes na string
/*Você recebe uma string scomposta por letras minúsculas em inglês. Uma remoção duplicada consiste em escolher duas letras adjacentes e iguais e removê-las.
Nós repetidamente fazemos remoções duplicadass até não podermos mais .
Retorne a string final após todas as remoções duplicadas terem sido feitas . Pode-se provar que a resposta é única.*/
/*Por exemplo, em "abbaca" poderíamos remover "bb" já que as letras são adjacentes e iguais, e este é o único movimento possível. O resultado deste movimento é que a string é "aaca", da qual apenas "aa" é possível, então a string final é "ca".*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char * removeDuplicates(char * s);
int procuraRemove(char * s);

int main()
{
    int remove = 1;
    char s[] = {"scmsmpfqvurocpprsiunqfqauanbedehsewvdluleadqabplcjdrmvtrkaouoglibvwlkhpewuavufbmtdkjtgedfrmditfkbabowgmxhefajurkjsvkbuassremowhdidsedvvsdemamulggcjhcumjllrltugfbjobuhphhjegbbkphgklrkcngchkujmvagaxojwuwvgqlhuqjucncbpkwedpnaghrommvgpduvrjpilmpppglvxmoubwrvhpjnpdeduanoofjlvintfewdwpnotrfvfacxebatbbvctjucuihepsqxiouwhguudhciqrmlmiqgdqvbvxrgrfuerhiqjqevfamewpwpiklplwpvudxfipxhemoimdgvwxdxkpasrdipoqakvwgoxondhrbkuejxdqgvrvoikhfujbrdmvblkfjnumekwoharggswgfoabnqpvbufuubwrrbjpfunfnekwidgnraagmjuasstotupnwbapieoohvturcehojukwbfgbbujkqpvxuwqxwetqkqumemhhorjqwnubecpvsmvompwqwdcnvnrnvdibktxmljgqidmbmkshfpefiipbkojqcebhkghqtdwxqboadmoqmsxmjgebgpgbnulhboopekcnrjqiegilnelatcpjvtemtwekuxqnjqnmwqvmjvjedjuntptekabgropxwnjwgbljuasixuhjkegxvjvxrbpsjrbqetepxbbpwvlrdifeplmlgvhgibudbdecbpokhvjdbvljpmpjoqdlaoxfansqlggicddnersjrlhgrukvsrpnijbhxbncfikptepdranmbtekdnjuiaeedbxqrkdorfftxogisoabvadttcqctsvelsxwrcgifakxsgtqligekadueatkitprgbmdmvtntfnibwtpabdievxsbchbcpgiwjtlfroibjskalkkvfmswucxiuxlosolrxomrrdnspgjsimlwbdwekbielpdhilibotqubfistmiddeihiwpdrasqsmwsnqkekglqmbfmcatrxpeuhjshwsaswbhdmknvqbleidboqwifxsdsbpttffwncklvlfnxdskkxpodxtjvbgrdcevurdivttwuevgqqmmwgacxgkkvpsluhefnqjsgtjmnmgvlkdhvrmagoxbbgadrmlxlfcbdjpiealmuoemtffuenhillfphdogrluhcobxecrroxssldicmxvdcqfcicahmijkgammbpuppjbtscqoegvqqsmibvfoagovtlsebthssbwmlvdfxbuirngnxpcgacxmnkrtfcqplsdrsqtsjjuskewnemkuiaiuqjvmdxjqgawfvofqhudiwfbvfjbdfmehifiepqhthidvvvvftgnpcltahbuatcqlcrixeqokkomejhwvcretcbireroxvoacirjrpkbllehilkgcaewxrfdwkdluhuaspsvvmdfjwaashihjbqwiebjsuopcwqdwlikpnapahojjkgohrdrjgcosvuogwnpkiflnbdqnsjqhxqopnrrqduwidbnlkrwtdiebsjhkdnqbdsvvhmuwjlukqriwhgnlockxeghnxhvscifvelfcrlocsjjtqshqobanmodbasuhhwdtapbosqwoenwgkxsfaisfofqcldimohllqgtpvwrjcxkcacqgomudnocuuffvujrcguhqrrkihwjlhxwxvalvvpetaexfnwadamjppuxvjlqxccaesjcvdltmbntimuvjaconwvsnlebagxjrhsnhtfmbetmmvnmsmdrrawivrfllwrxdsxrqicqqwlwtowrswkovbevaprplxgefnfbmhpwurawkqlhdmdcggeucbutfvbnlohrxlgjjtghmsiesalpxlidxdckvtffjxcvujuutwsvgfbceawmvlnmtjaqwfqktgjkimvmpipmuqswepokmcxudxckvbuovwathbnfhdkbbfxtoajxxvkhcjtcoigweleuudqkjngpsqmpobdnlibqddxgmacwlqicuxbjaaictguuafptegkmmbdkmnmrftrakjoeickhpknhbqrsnmphahkbkkafapkcdujavwlqlbretfwqdvgferahrukmaiaeteqqdxettxngmcjqcgrscesiogotxbflggfkptumshfshsxonkojikliffxncqashgvidfegvvveibdxrwxhqqqubelqwicvtpmhfjsuxgraddjwsvbqqluphauwonjrnngdqcrvgonsumwxlmqilvuosmheglbrkgxqqgoceafniafwjxilvddlqvjgswfjgddbbaejfbnhkddaiinetknetxuagsbvetwdauavouakfrlatwkapuxexffvotskshukxonkdomchwrsxtntxhuijlasxnltbwakuchvaclnmgstpliqgnadvgjlunquajaxkudbqvlfofbgjmrvauqbpkmmjfgbbxwenamsasgicalxgpkurgigssujcsbxqchgrsgntwjpnjtkfsqcfjcpddxntqtjdgirsggmomijcfvuqralqpvwnipvidddmqtinjqfvrprvagqmhushgccfwkngaskxdfbfvouejksspjkvrjnvbxmxisixjwrcmswnpptoxvjfedpockwwuxkodeertsmphnmldmqqxtkkuxsmhvkwshpicutxtlakhuhlflovwciwmbpclnmbjspgcokvlmhjaksxsascamjeogsvlvctmvhpgwnpjkpwakleefolihxxqkajcdgjhlkntaxkhquvikuhqbqdtvhfuxejnbfnwamvuiojtkimoucddvupulfsidckaftvfrjkokehxnjvofaehxelivmqwcoqwrleacorvbwkbmculsegktwkshbmmxvpdctokvwgedhvtuqocnifgdvrhfalmockmunijqnuxcvetqfpotbfbgwmclnieusvfdomrxqatlkmmuxlmpldnntganexhuxwblbquejoeklxjvkfqxkjqgsmuoimatppnhuxhoxbnmmdigasugbvvfxsdugdvdnnmfbmootgltalemhfpancpnmlbjcrblwdsqfwnklrblvtjckutqkfuspublqqavvgnlugigkvusfxtnoamluahrtrpuuggvoswlkrdnuhplvlnpvqpggqdvunibjowxvsefcetlfdpkjenhvgilwsgsxnigumwaxlalbbkvsehcmmgosxchwjlfpfkpjurewqbslovgoperlbmsgwcocrwsaqcqekdvjxjwuwjsopbrcgdppateigtdhtvnalikbkulxwaomblhvppiijrfdevwgbpkskumufxfkixogropajervfkvwpcxuilkwcdbnggppbtmpdvvwooxdhxpoenrksgtirbvagehtggpmsuvudrfnlxjogcavtlxeltckufqjsoqalidgnsxhxtvmjvrkihevktpgsgvxrnfxbvdqxtcofsjcbkxffgeilgfavtdhxbbfkgjofjsesgxncfxiwkubtqcerhpwivbxpiqldirxbtebalebocauffshroliruqxxggewmolpwukqoclcimenkaucouquelemenfakksqstlelwkfamwhbahpqouxifhtakshmtsxuvrkgdtexmhxpgvvdnovlkwxtcgwpuorigqndnrdrhibjqqaqetstpmfuxwrqsdsbserhranjlacrhwewjokdhfruwoerienlerduluxdsjnnjdexhnrphghclslilvxmksvpwkvekqvhjkvhbkmssscacfcxocdngmnnwftqvjqnuwsdekgcenocovgmnqpuotfixresqqkbvoqwvjkkstbnfusjvbfvmltfhtmhpjvjitlvwcgohjffshsmbebtfhkrpojkghoxklgeetwcqkpvqjcpgkidnfhovwfirhcrxbwolwusiscjeqoahbgaihesmheeuvujrbpppqfklolwlwssaexhcbhpbgudleivpieeeuwowawaxatawhwuhrsdhwxbbkkqkjkroqcsnpwsnsmamxqcdblrstbqergoqifrqgvdcuirraqfhwivrxfupcqxgwjkucarilddtniapnftksmchmesjvwafnvktraeatahmvrmlohgsxnmxhngvsxplbirqdrpwsidqqaqihqjbisqotstonjjnavdqegvutqllcabmuvkorvkbtrprrwcxmqewgedxdlusapcralecglfcumnrbkfnsfiohhmtovainhqvivlelxgwcbjsekhlfqlfkcfeqkmrouwkrhlfngajatxrlstfdgjwekcoewncvtbwuvalpuppuxlbmwfpwcgwilovinfgiqmlitgjovrtaxbwsrtulpoakavngukschugpvbemmhtjbnvriwcwtfiowujdvgrqlfthavphvactpdbggnlkcptibhhsghanrcocpxpsgflrpxpmbbevwimnujjjkhsvuqcegrokrntbuvcxsjkbuuqqewecfulercftbqtslcpvdrpeaxpdrisoelnkdqihmucjuiqgxqjcwhjnfxqoagwcbugvrbuqremtlnjccuolkleqggjqnlbapmmgrcmgltbntmklqjswejfrohgdulwecalcrwlshxldwxaemmbvxnhcchkubtkcftxoutnsiepiklxjtjpfhmpbgkdhqnqpncttwmxrtfbrkfjgblhsqiijgtuqwhvofifadeelmhnkchuibppxgwgxnxisgtlukcaiabjvwghxwpmkqaccgkwnqrvclgrlampgpwrcpfdedpeikklfkblbcfvetfqjtaahopaoianmdvqpckpfanshabfeclpjgvvpiilnamquutfcvutvlmojoobfctxanvtjjvfmjmkqjpovgdbdxidvplnfitorwmwtnsdopffuglieduoraxwgarvgrfpqdpkpitixqlpthfoenkwedlsbfpvuixprrsdcheqeojccjauqlkvickmijwrfrubrdavhejixfudvoppepahitoprrnemapctwwuungtpdpgauqtfwhpsbvpijoumrwntohddvxwvkoxpgwcoetdaqsrhuvdkjugvoairqaepgpkvankterfheajepppbkncwluncsgcqvdlpoipilmtdbfrkoisxknmrriqjqdsubborefecebxhuepvmdbomhqtlhtuuuthwsohpxfmmugqpqpkouatublogotnmnogrvjejsoshimkapuehqtkgwrqoqujllcmoeboakvrasfbkmsxnloxgcuugscmvqawbtuphldlfnfbjtwisqvfbjdhtprjwrwwnxemcrwoxwivbqdjsemkshxdamnwktxkhtganqjgvaksxhnrskwqmagotfsfgiqndmojnejfrphunmbbwpblnaeuwnlkmwummwqrejjbqbcprtdwcoxrjtthnaotspqchmqvitgonqrpoiffbunekocnvdfstjhlxcciehcwfiwxapgcqeqrntsbksgndwvdrwbauhexugwuduhpsdcmhhjaiidohmxhrjlheiomfnocmdwsmuirlgtucsjbjwqrtjdsjomjvsavnqggsewlfvdtfdmupxuqksevvwktaqrqmhuhqxqibgvbuaabdnivlpdeosvnrmfiefdsbarclgwinubvldaojfmsphblfcpbbeicslxwxkbgrelmsexwbheeekarivvppjwlofvhcucghdrcvwbbpcvwbnqevssgsirjskodpbwujgjkwmsmgjumkovxrujjwwgbsfxuboavuankksxslbekdhcoqpafaviwrtvpgnfedoluommpkgtdbwtgvrrotcmumxchkeqvddnungupwdmupvncftbitsfihwdcpwonimqqtmlpvmsjjctgtenouhqfvlukswrhvfasecwsqgdodxspnfpncppptdreisqxqrriuuqeonjwjcvhnnebbubkvroeeeejsvpdqovkbebwhwaupfhwouhdwkpoksmskuwkcuswfhakcwqbiewqujpnljhvwpruckcqickxaeaweirteeucxjvmatewmxjggehqvukgmegwdpffhrnbdpuvqmafrvxrugapfonrfvwfshslmambegqsigbghpqlwdlbeuptjllifdmjqvgwwegkeibveqhxaqcbpkvirrtdjroeotalvmjghevnlejrqikvinlmmejkiemxdgmwosfmwxjlapbwqihpnxtmuiqaaidollxjerxonujthndbumgmbnddghgtmjggcwvrlhstxprbusuwkwiiiepogafnqtbctcsjhhdebfnaucxrtvuggosppvktisrgcecxuffpxkinkjjpolfliaiewkbqasjwvxjvxvnherimrtvlfuxlixoqoehcehwhoakastginpqbpeprvfocenxinxwdjndmkcdmttuhfxdahqewccnuwqphvwsqsafbmkoefbepbgwmglhnporuukdjkvrntnxcblrvmbrufxwkwrvcbvhqkrpkjrwnaonmvkodexhtfpfgnprbdvbskiwhowmnfqectkckrhdoesqmgpxhdhmorcmcmhjrwxprqaboivbdhddxnwmxsjmsufnsbjpvqqstaqpcuomwrokewadnxhfqoewaoxuvfnkoonamaeqjxiahvsjgemlfkkdscgsedllnptigsebkfvtewwrvgfcvhvodhbwifxhfpxdevsemwqghgbiwqfouoiwhcfutpdnabnuuotvmxnulhqrnqjcvexulonqrvfwekabqpjhumjkvhnihpnewwggkawgamxifgemngbokbivbrgrpmmojwiqauecsgowfihdhoqgcbfxtsfcjbsfkklmbnshmbhnsfcicsieoinvhmaurtevpnsjkielsanaxjuabjxeuedlamsnmfwlctrigbhaqpterhopkuhjxpuflxoivmlbqrehrdxurkpmkmpjxqgpevdhmascruhenjpsqtpjloefidqcfcgtnefuolbgcihxvromnvdeifnjhrawpuvqiwwcpmwjgnxamdfbxeajmnqxrkbrdmvcrhqmjhhoihkcnnrgxncunjiiekhotnuwcvsfjrxbfbfqfcuglmmrnvbcdextulvxbsoktecxiadiihlfgelubvobtnvkrtlkjsqacwdtfajmrgcaescrfvnawiuqqhucotvresabaecjgvnkbkotncjlkkastfdtfxjklmmgwrdurobqcpsqvwwhlxwspaesbkhxeitoclxhhhivsglkipqxtlknauklgrmekcreintpdlhowlvpdidhijxxkfdijatflhcemmsqtgtgqjljsvtufgseqhsaulafjcccderfjfgjwfjvqcmbonghxwteonrcjgvdqamecsgmlcuxdmktqlqgdxccqtxwhrpdxfgqcdncughtfnjnguteavdfqqbxgounfgdevlbxmcxntlvmutuubukkqkqxecjffjagggeipfqjrjtlpnotealuxllldxaxtirikqurbjfcslvobwwwdvciwpmaitoqtxrpvndexddolnacajxplxtbdthqwrxmcdnhdrhpdofpbeqkitotxdtljtrqtnxgdqieqrlompqlvscstixwvtedmsflrtdsccxkxicmdspeonqxhlfuhvdeboaxfxffmeffvckvgdppwqxfhjejcmuldqgptvtkllpbgtggiflitwmwagjicuttopsgokpnosisghkcvvqdpgrjnnqxkrfawfjceqwlggftakjokgreojlhctmrqiupaxwnpfnhbtjsbbjfkvdhouxwducjwmfdhqnnueoobujjnhvlborabepsvlfubafbpvmmhkhdngjvixbftmqtmurfsvrpmkwufkuhtrclovmlohjoneuttiqgbgeefnoimsmcvwfbkfovktbdscqwsuxolbxigghcqsnbsotbubmijnnhwbiwemutodjxuhhnvwgiduxaqfsahcrxwobapmbbvxeflnaoqjicxexjtxdjqxjnmfhqvjekmsmopfqiuqknq"};
    
    printf(":%s\n", removeDuplicates(s));

}

char * removeDuplicates(char * s){
    int remove = 1;
    
    while (remove == 1){    //Verifca letras dupicadas e remove até não exitir mais
        remove =  procuraRemove(s);
    }
    
    return s; 
}

int procuraRemove(char * s){
    int indice = 0, encontrou = 0;

    for (int i = 0; i < strlen(s) - 1; i++){    //Percorre palavra
        if (s[i] == s[i+1]){
            indice = i;     // Indica o indíce da letra duplicada
            encontrou = 1;
        }
        
        if (encontrou == 1 && s[i] != s[i+1]){  //Contabiliza apenas uma sequencia
            break;
        }
    }
    indice++;   // Vai para última letra

    // Se existe letras duplicadas, remove elas
    if (encontrou == 1){ 
        if (strlen(s) == 2){ //Remove todas letras
            strcpy(s, "");
            return 0;
        }
        for (int i = 0; i < strlen(s); i++){
            if ( i > indice - 2 && i < strlen(s) - 1){
                s[i] =  s[i + 2];
            }
        }
       return 1;
    } 
    return 0;
}
